blog/urls.py
# -*- coding:utf-8 -*-
# author: SM0558
# datetime: 2022/1/12 16:21
# software: PyCharm

from django.urls import path

from . import views

# 正在部署的应用的名称
app_name = 'blog'
urlpatterns = [
    path('list/', views.blog_list, name='blog_list'),
    path('blog-detail/<int:id>/', views.blog_detail, name='blog_detail'),
    path('blog-create/', views.blog_create, name='blog_create'),
    path('blog-delete/<int:id>/', views.blog_delete, name='blog_delete'),
    path('blog-update/<int:id>/', views.blog_update, name="blog_update"),
]

userprofile/urls.py
# -*- coding:utf-8 -*-
# author: SM0558
# datetime: 2022/1/18 14:08
# software: PyCharm
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/<int:id>/', views.user_logout, name='logout'),
    path('register/', views.user_register, name="register"),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

xwp_top/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('', views.index, name='index'),
    path('message_log/', include('messagelog.urls', namespace='messagelog')),
]

userprofile/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    # 与User模型构成一对一的关系
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone = models.CharField(max_length=20, blank=True)
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return 'user{}'.format(self.user.username)


# 信号接受函数,每当新建User实例时自动调用
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


# 信号更新函数,每当更新User实例时自动调用
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

userprofile/forms.py
# -*- coding:utf-8 -*-
# author: SM0558
# datetime: 2022/1/18 13:54
# software: PyCharm
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserLoginForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(forms.ModelForm):
    # 复写 User 的密码
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密码输入不一致,请重试。")


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'avatar', 'bio')

userprofile/views.py
# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
import hashlib

from userprofile.forms import UserLoginForm, UserRegisterForm, ProfileForm
from userprofile.models import Profile
from .models import User


def user_login(request):
    if request.method == "POST":
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data洗出合法数据
            data = user_login_form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个user对象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                login(request, user)
                return redirect("blog:blog_list")
            else:
                return HttpResponse("账号或密码输入有误,请重新输入")
        else:
            return HttpResponse("账号或密码输入不合法")
    elif request.method == "GET":
        user_login_form = UserLoginForm()
        context = {'from': user_login_form}
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好数据后立即登录并返回博客列表页面
            login(request, new_user)
            return redirect("blog:blog_list")
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = {'form': user_register_form}
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


@login_required(login_url='/userprofile/login/')
def user_delete(request, id):
    user = User.objects.get(id=id)
    if request.user == user:
        logout(request)
        user.delete()
        return redirect("blog:blog_list")
    else:
        return HttpResponse("你没有删除操作的权限。")


@login_required(login_url='/userprofile/login/')
def user_logout(request, id):
    user = User.objects.get(id=id)
    if request.user == user:
        logout(request)
        return redirect("blog:blog_list")
    else:
        return HttpResponse("你没有操作的权限。")


@login_required(login_url='/userprofile/login/')
def profile_edit(request, id):
    user = User.objects.get(id=id)
    # user_id是OneToOneField自动生成的字段
    profile = Profile.objects.get(user_id=id)

    if request.method == 'POST':
        # 验证修改数据者是否为本人
        if request.user != user:
            return HttpResponse("你没有权限修改次用户信息")

        profile_form = ProfileForm(data=request.POST)
        if profile_form.is_valid():
            # 取得清洗后的合法数据
            profile_cleaned_data = profile_form.cleaned_data
            profile.phone = profile_cleaned_data['phone']
            profile.bio = profile_cleaned_data['bio']
            profile.save()
            return redirect("userprofile:edit", id=id)

        else:
            return HttpResponse("注册表单输入有误,请重新输入")

    elif request.method == "GET":
        profile_form = ProfileForm()
        context = {'profile_form': profile_form, 'profile': profile, 'user': user}
        return render(request, 'userprofile/edit.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


def hash_code(s, salt='mysite_login'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()


class LoginView(generic.FormView):
    model = User
    template_name = 'userprofile/login.html'
    form_class = UserLoginForm

    def get(self, request, *args, **kwargs):
        if request.session.get('is_login', None):
            return redirect("/")
        else:
            login_form = self.form_class()
            return render(request, self.template_name, locals())

    def post(self, request, *args, **kwargs):
        login_form = self.form_class(request.POST)
        message = "请检查填写的内容！"
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            try:
                user = User.objects.get(name=username)
            except:
                message = "用户名不存在！"
            else:
                if user.password == hash_code(password):
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    request.session['user_name'] = user.name
                    return redirect('/')
                else:
                    message = "密码不正确！"
        return render(request, self.template_name, locals())

userprofile/templates/userprofile/edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}
User
{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">Username {{ user.username }}</div>
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group col-md-4">
                    <label for="phone">phone</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>
                <div class="form-group col-md-4">
                    <label for="bio">bio</label>
                    <textarea type="text" class="form-control" id="bio" name="bio"
                              rows="12">{{ profile.bio }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

userprofile/templates/userprofile/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Login
{% endblock title %}
{% block content %}
<div class="container">
    <div class="col-md-4 col-md-offset-4">
        <br>
        <form method="post" action=".">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
        <h5>No account yet?</h5>
        <h5>Click <a href='{% url "userprofile:register" %}'>here</a> to register.</h5>
        <br>
    </div>
</div>
{% endblock content %}

userprofile/templates/userprofile/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}
register
{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group col-md-4">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>
                <div class="form-group col-md-4">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <div class="form-group col-md-4">
                    <label for="password2">Password again</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
            {# #}
        </div>
    </div>
</div>
{% endblock content %}