blog/urls.py
# -*- coding:utf-8 -*-
# author: SM0558
# datetime: 2022/1/12 16:21
# software: PyCharm

from django.urls import path

from . import views

# 正在部署的应用的名称
app_name = 'blog'
urlpatterns = [
    path('list/', views.blog_list, name='blog_list'),
    path('blog-detail/<int:id>/', views.blog_detail, name='blog_detail'),
    path('blog-create/', views.blog_create, name='blog_create'),
    path('blog-delete/<int:id>/', views.blog_delete, name='blog_delete'),
    path('blog-update/<int:id>/', views.blog_update, name="blog_update"),
]

xwp_top/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('', views.index, name='index'),
    path('message_log/', include('messagelog.urls', namespace='messagelog')),
]

blog/models.py
import django.utils.timezone
from django.db import models

# 导入内建的User模型
from django.contrib.auth.models import User


# 博客数据模型
class BlogPost(models.Model):
    # 博主
    blogger = models.ForeignKey(User, on_delete=models.CASCADE)

    # 博客标题
    title = models.CharField(max_length=200)

    # 博客内容
    body = models.TextField()

    # 创建时间
    created = models.DateTimeField(default=django.utils.timezone.now)

    # 更新时间
    updated = models.DateTimeField(auto_now=True)

    # 浏览次数
    total_views = models.PositiveIntegerField(default=0)

    # 内部类，给model定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # ’-created‘ 表明数据应该以倒叙排列
        ordering = ('-created',)

    def __str__(self):
        return self.title

blog/forms.py
# -*- coding:utf-8 -*-
# author: SM0558
# datetime: 2022/1/17 15:57
# software: PyCharm
from django import forms
from .models import BlogPost


# 写文章表单类
class BlogPostFrom(forms.ModelForm):
    class Meta:
        # 数据来源
        model = BlogPost
        # 表单字段
        fields = ('title', 'body')

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import BlogPost
import markdown
from .forms import BlogPostFrom
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


# 文章列表视图
def blog_list(reuqest):
    # 取出所有文章
    blogs_list = BlogPost.objects.all()
    # 根据GET请求中查询条件
    # 返回不同排序的对象数组
    if reuqest.GET.get('order') == 'total_views':
        blogs_list = BlogPost.objects.all().order_by('-total_views')
        order = 'total_views'
    else:
        blogs_list = BlogPost.objects.all()
        order = 'normal'
    # 每页显示一篇文章
    paginator = Paginator(blogs_list, 3)
    # 获取url中的页码
    page = reuqest.GET.get('page')
    # 将导航对象相应的页码内容返回给blogs
    # blogs = paginator.get_page(page)
    blogs = paginator.get_page(page)
    # 添加Markdown功能
    for blog in blogs:
        blog.body = markdown.markdown(blog.body,
                                      extensions=['markdown.extensions.extra', 'markdown.extensions.codehilite', ])
    # 取出需要传递的模板对象
    context = {'blogs': blogs, 'order': order}
    # render方式返回context对象
    return render(reuqest, 'blog/list.html', context)


# 文章详情视图
def blog_detail(request, id):
    blog = BlogPost.objects.get(id=id)
    blog.total_views += 1
    blog.save(update_fields=['total_views'])
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    blog.body = md.convert(blog.body)
    context = {'blog': blog, 'toc': md.toc}
    return render(request, 'blog/detail.html', context)


# 增加文章视图
@login_required(login_url='/userprofile/login')
def blog_create(request):
    if request.method == "POST":
        blog_post_form = BlogPostFrom(data=request.POST)
        if blog_post_form.is_valid():
            new_blog = blog_post_form.save(commit=False)
            # new_blog.blogger = User.objects.get(request.user.id)
            new_blog.blogger_id = request.user.id
            new_blog.save()
            return redirect('blog:blog_list')
        else:
            return HttpResponse("表单内容有误,请重新填写")

    else:
        blog_post_form = BlogPostFrom()
        context = {'blog_post_form': blog_post_form}
        return render(request, 'blog/create.html', context)


def blog_delete(request, id):
    blog = BlogPost.objects.get(id=id)
    blog.delete()
    return redirect('blog:blog_list')


def blog_update(request, id):
    blog = BlogPost.objects.get(id=id)
    if request.method == "POST":
        blog_post_form = BlogPostFrom(data=request.POST)
        if blog_post_form.is_valid():
            blog.title = request.POST['title']
            blog.body = request.POST['body']
            blog.save()
            return redirect("blog:blog_detail", id=id)
        else:
            return HttpResponse("表单内容有误,请重新填写")
    else:
        blog_post_form = BlogPostFrom()
        context = {'blog': blog, 'blog_post_form': blog_post_form}
        return render(request, 'blog/update.html', context)

blog/templates/blog/create.html
{% extends "base.html" %}
{% load static %}
{% block title %}
make
{% endblock title %}
{% block  content %}
<div class="container">
    <div class="col-12">
        <br>
        <form method="post" action=".">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" id="title" name="title">
            </div>
            <div class="form-group">
                <label for="body">Body</label>
                <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">submit</button>
        </form>
    </div>
</div>
</div>
{% endblock content %}

blog/templates/blog/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
blog
{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-9">
            <h1 class="col-12 mt-4">{{ blog.title }}</h1>
            <div class="col-12 alert alert-success">blogger: {{ blog.blogger }}</div>
            {% if user == blog.blogger %}
            .<a href="#" onclick="confirm_delete()">Delete</a>
            .<a href="{% url " blog:blog_update" blog.id %}">Edit</a>
            {% endif %}
            <div>
                &nbsp;&nbsp;views: {{ blog.total_views }}
            </div>
            <div class="col-12">
                <p>{{ blog.body|safe }}</p>
            </div>
        </div>
        {# contents #}
        <div class="col-3 mt-4">
            <h4>
                <strong>contents</strong>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </h4>
        </div>
    </div>
</div>
<script>
    function confirm_delete() {
        var r = confirm("Wanna delete?");
        if (r === true) {
            window.location = '{% url "blog:blog_delete" blog.id %}';
        }
    }
</script>
{% endblock content %}

blog/templates/blog/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Blog
{% endblock title %}
{% block content %}
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'blog:blog_list' %}">
                    New
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'blog:blog_list' %}?order=total_views">
                    Hot
                </a>
            </li>
        </ol>
    </nav>
    <div class="row mt-2">
        {% for blog in blogs %}
        <div class="col-4 mb-4">
            <div class="card h-100">
                <h4 class="card-header">{{ blog.title }}</h4>
                <div class="card-body">
                    <p class="card-text">{{ blog.body|slice:'50'|safe }}...</p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'blog:blog_detail' blog.id %}" class="btn btn-info">read</a>
                    <a href="{% url 'blog:blog_delete' blog.id %}" class="btn btn-warning">delete</a>
                    <span>
                            <small class="col align-self-end" style="color: gray;">
                                views: {{ blog.total_views }}
                            </small>
                            </span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{#
<div class="container mt-3">#}
    {#
    <table class="table">#}
        {#
        <tbody>#}
        {# {% for blog in blogs %}#}
        {#
        <tr>#}
            {#
            <td>{{ blog.title }}</td>
            #}
            {#
            <td>{{ blog.body|slice:'100' }}</td>
            #}
            {#
            <td class="card-footer">#}
                {# <a href="{% url 'blog:blog_detail' blog.id %}" class="btn btn-primary">read</a>#}
                {#
            </td>
            #}
            {#
        </tr>
        #}
        {# {% endfor %}#}
        {#
        </tbody>
        #}
        {#
    </table>
    #}
    {#
</div>#}
<div class="pagination row">
    <div class="m-auto">
        <span class="step-links">
            {% if blogs.has_previous %}
                <a href="?page=1" class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ blogs.previous_page_number }}"
                   class="btn btn-secondary"
                >
                    {{ blogs.previous_page_number }}
                </a>
            {% endif %}
            <span class="current btn btn-danger btn-lg">
                {{ blogs.number }}
            </span>
            {% if blogs.has_next %}
                <a href="?page={{ blogs.next_page_number }}"
                   class="btn btn-secondary"
                >
                    {{ blogs.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ blogs.paginator.num_pages }}"
                   class="btn btn-success"
                >
                    {{ blogs.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}

blog/templates/blog/update.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Edit
{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ blog.title }}">

                </div>
                <div class="form-group">
                    <label for="body">Body</label>
                    <textarea type="text" class="form-control" id="body" name="body"
                              rows="12">{{ blog.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}