blog/urls.py
# -*- coding:utf-8 -*-
# author: SM0558
# datetime: 2022/1/12 16:21
# software: PyCharm

from django.urls import path

from . import views

# 正在部署的应用的名称
app_name = 'blog'
urlpatterns = [
    path('list/', views.blog_list, name='blog_list'),
    path('blog-detail/<int:id>/', views.blog_detail, name='blog_detail'),
    path('blog-create/', views.blog_create, name='blog_create'),
    path('blog-delete/<int:id>/', views.blog_delete, name='blog_delete'),
    path('blog-update/<int:id>/', views.blog_update, name="blog_update"),
]

messagelog/urls.py
# -*- coding:utf-8 -*-
# author: SM0558
# datetime: 2022/1/20 15:30
# software: PyCharm
from django.urls import path
from . import views

app_name = 'message_logs'

urlpatterns = [
    path('post-message_log/', views.post_message_log, name='post_message_log'),
]

userprofile/urls.py
# -*- coding:utf-8 -*-
# author: SM0558
# datetime: 2022/1/18 14:08
# software: PyCharm
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/<int:id>/', views.user_logout, name='logout'),
    path('register/', views.user_register, name="register"),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

xwp_top/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('', views.index, name='index'),
    path('message_log/', include('messagelog.urls', namespace='messagelog')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'markdown/css/monokai.css' %}">
</head>
<body>
{% include 'header.html' %}
{% block content %}{% endblock content %}
{% include 'footer.html' %}
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/footer.html
{% load static %}
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-start text-white">footer</p>
    </div>
</footer>

templates/header.html
<head>
    {% if user.is_authenticated %}
    <script>
        function user_delete() {
            const r = confirm("Wanna delete this user?");
            if (r === true) {
                window.location = '{% url "userprofile:delete" user.id %}';
            }
        }
    </script>
    <title></title>
    {% endif %}
</head>
<nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col shadow-sm">
                <nav class="navbar p-0 navbar-expand-sm navbar-light bg-white">
                    <a class="navbar-brand" href="{% url 'index' %}">misldy.top</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#mynavbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="mynavbar">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:blog_list' %}">博客</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'blog:blog_create' %}">New</a></li>
                            <li class="nav-item">
                                <a class="nav-link" href="javascript:void(0)">链接</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav nav-item dropdown" style="float: right; margin-right: -15px">
                            {% if user.is_authenticated %}
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                               data-bs-toggle="dropdown">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url " userprofile:edit" user.id %}">User</a>
                                <a class="nav-link" href="{% url 'messagelog:post_message_log' %}">comment</a>
                                <a class="dropdown-item" href="{% url " userprofile:logout" user.id %}">Exit</a>
                                <hr class="dropdown-divider">
                                <a class="dropdown-item" href="#" onclick="user_delete()">Delete</a>
                            </div>
                            {% else %}
                            <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                            <a class="nav-link" href="{% url " userprofile:register" %}">注册</a>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="form-check-inline my-2 my-lg-0 nav-item dropdown">
                        {% if user.is_authenticated %}
                        {% else %}
                        {% endif %}
                    </div>
                </nav>
            </div>
        </div>
    </div>
</nav>